INIT_O_FILES := \
    $(BUILD_DIR)/asm/init.o

EXTAB_O_FILES := \
    $(BUILD_DIR)/asm/extab.o

EXTABINDEX_O_FILES := \
    $(BUILD_DIR)/asm/extabindex.o

TEXT_O_FILES := \
    $(BUILD_DIR)/asm/text/sr_getappname.o \
    $(BUILD_DIR)/asm/text/sr_common.o \
    $(BUILD_DIR)/asm/text/sr_revision.o \
    $(BUILD_DIR)/asm/text/main.o \
    $(BUILD_DIR)/asm/text/gf_3d_scene.o \
    $(BUILD_DIR)/asm/text/gf_3d_scene_event.o \
    $(BUILD_DIR)/asm/text/gf_3d_scene_light_resource.o \
    $(BUILD_DIR)/asm/text/gf_area.o \
    $(BUILD_DIR)/asm/text/gf_area_manager.o \
    $(BUILD_DIR)/asm/text/gf_archive_load_thread.o \
    $(BUILD_DIR)/asm/text/gf_archive.o \
    $(BUILD_DIR)/asm/text/gf_file_io.o \
    $(BUILD_DIR)/asm/text/gf_archive_file.o \
    $(BUILD_DIR)/asm/text/gf_archive_db.o \
    $(BUILD_DIR)/asm/text/gf_archive_manager.o \
    $(BUILD_DIR)/asm/text/gf_app.o \
    $(BUILD_DIR)/asm/text/gf_boot_task.o \
    $(BUILD_DIR)/asm/text/gf_camera.o \
    $(BUILD_DIR)/asm/text/gf_camera_controller.o \
    $(BUILD_DIR)/asm/text/gf_callback.o \
    $(BUILD_DIR)/asm/text/gf_decomp.o \
    $(BUILD_DIR)/asm/text/gf_draw.o \
    $(BUILD_DIR)/asm/text/gf_effect.o \
    $(BUILD_DIR)/asm/text/gf_error_manager.o \
    $(BUILD_DIR)/asm/text/gf_error_check.o \
    $(BUILD_DIR)/asm/text/gf_file_io_handle.o \
    $(BUILD_DIR)/asm/text/gf_file_io_request.o \
    $(BUILD_DIR)/asm/text/gf_file_io_thread.o \
    $(BUILD_DIR)/asm/text/gf_file_io_manager.o \
    $(BUILD_DIR)/asm/text/gf_framebuffer.o \
    $(BUILD_DIR)/asm/text/gf_gameframe_counter.o \
    $(BUILD_DIR)/asm/text/gf_heap_manager.o \
    $(BUILD_DIR)/asm/text/gf_keep_fb.o \
    $(BUILD_DIR)/asm/text/gf_loupe.o \
    $(BUILD_DIR)/asm/text/gf_memory_pool.o \
    $(BUILD_DIR)/asm/text/gf_memory_util.o \
    $(BUILD_DIR)/asm/text/gf_module.o \
    $(BUILD_DIR)/asm/text/gf_pad.o \
    $(BUILD_DIR)/asm/text/gf_model.o \
    $(BUILD_DIR)/asm/text/gf_pad_queue.o \
    $(BUILD_DIR)/asm/text/gf_pad_thread.o \
    $(BUILD_DIR)/asm/text/gf_rumble.o \
    $(BUILD_DIR)/asm/text/gf_scene.o \
    $(BUILD_DIR)/asm/text/gf_task.o \
    $(BUILD_DIR)/asm/text/gf_task_scheduler.o \
    $(BUILD_DIR)/asm/text/gf_texconv.o \
    $(BUILD_DIR)/asm/text/gf_thread.o \
    $(BUILD_DIR)/asm/text/gf_thumbnail.o \
    $(BUILD_DIR)/asm/text/gf_copyefb.o \
    $(BUILD_DIR)/asm/text/gf_shutdown_manager.o \
    $(BUILD_DIR)/asm/text/gf_sys_recorder2.o \
    $(BUILD_DIR)/asm/text/gf_slow_manager.o \
    $(BUILD_DIR)/asm/text/gf_mii.o \
    $(BUILD_DIR)/asm/text/gf_now_loading.o \
    $(BUILD_DIR)/asm/text/gf_homemenu.o \
    $(BUILD_DIR)/asm/text/gf_crypto_aes.o \
    $(BUILD_DIR)/asm/text/gf_video.o \
    $(BUILD_DIR)/asm/text/gf_system_callback.o \
    $(BUILD_DIR)/asm/text/gf_collection_io.o \
    $(BUILD_DIR)/asm/text/gf_capture_util.o \
    $(BUILD_DIR)/asm/text/gf_crypto_esp.o \
    $(BUILD_DIR)/asm/text/gf_vc_launch.o \
    $(BUILD_DIR)/asm/text/gf_monitor.o \
    $(BUILD_DIR)/asm/text/gf_resource_loader.o \
    $(BUILD_DIR)/asm/text/mt_common.o \
    $(BUILD_DIR)/asm/text/mt_vector.o \
    $(BUILD_DIR)/asm/text/mt_vector_old.o \
    $(BUILD_DIR)/asm/text/mt_matrix.o \
    $(BUILD_DIR)/asm/text/mt_quaternion.o \
    $(BUILD_DIR)/asm/text/mt_prng.o \
    $(BUILD_DIR)/asm/text/mt_trig.o \
    $(BUILD_DIR)/asm/text/mt_spline.o \
    $(BUILD_DIR)/asm/text/mt_coll2d.o \
    $(BUILD_DIR)/asm/text/mt_coll3d.o \
    $(BUILD_DIR)/asm/text/mt_prng_log.o \
    $(BUILD_DIR)/asm/text/module.o \
    $(BUILD_DIR)/asm/text/ut_nw.o \
    $(BUILD_DIR)/asm/text/ut_relocate.o \
    $(BUILD_DIR)/asm/text/ut_bitarray.o \
    $(BUILD_DIR)/asm/text/ut_list.o \
    $(BUILD_DIR)/asm/text/ut_archive_manager.o \
    $(BUILD_DIR)/asm/text/ut_scnmdl_mod.o \
    $(BUILD_DIR)/asm/text/ip_human.o \
    $(BUILD_DIR)/asm/text/ip_padconfig.o \
    $(BUILD_DIR)/asm/text/ip_switch.o \
    $(BUILD_DIR)/asm/text/ip_network_producer.o \
    $(BUILD_DIR)/asm/text/ip_padrec.o \
    $(BUILD_DIR)/asm/text/gm_global.o \
    $(BUILD_DIR)/asm/text/gm_lib.o \
    $(BUILD_DIR)/asm/text/gm_data_itemswitch.o \
    $(BUILD_DIR)/asm/text/gm_data_collection.o \
    $(BUILD_DIR)/asm/text/gm_hide_lib.o \
    $(BUILD_DIR)/asm/text/gm_syssave_task.o \
    $(BUILD_DIR)/asm/text/effect.o \
    $(BUILD_DIR)/asm/text/ef_manager.o \
    $(BUILD_DIR)/asm/text/ef_particle.o \
    $(BUILD_DIR)/asm/text/ef_particle_counter.o \
    $(BUILD_DIR)/asm/text/ef_screen.o \
    $(BUILD_DIR)/asm/text/ef_screen_handle.o \
    $(BUILD_DIR)/asm/text/ec_mgr.o \
    $(BUILD_DIR)/asm/text/ec_effect_work.o \
    $(BUILD_DIR)/asm/text/ec_resource.o \
    $(BUILD_DIR)/asm/text/ec_trace_mgr.o \
    $(BUILD_DIR)/asm/text/ec_trace.o \
    $(BUILD_DIR)/asm/text/ms_message.o \
    $(BUILD_DIR)/asm/text/ms_resfont.o \
    $(BUILD_DIR)/asm/text/ms_tag.o \
    $(BUILD_DIR)/asm/text/ms_char_writer.o \
    $(BUILD_DIR)/asm/text/ms_text_writer_base.o \
    $(BUILD_DIR)/asm/text/ms_texobj.o \
    $(BUILD_DIR)/asm/text/snd_system.o \
    $(BUILD_DIR)/asm/text/snd_bgmsys.o \
    $(BUILD_DIR)/asm/text/snd_3d_generator.o \
    $(BUILD_DIR)/asm/text/snd_init_thread.o \
    $(BUILD_DIR)/asm/text/snd_load_thread.o \
    $(BUILD_DIR)/asm/text/snd_heapsys.o \
    $(BUILD_DIR)/asm/text/snd_doubutsugo_task.o \
    $(BUILD_DIR)/asm/text/mv_THPAudioDecode.o \
    $(BUILD_DIR)/asm/text/mv_THPDraw.o \
    $(BUILD_DIR)/asm/text/mv_THPPlayer.o \
    $(BUILD_DIR)/asm/text/mv_THPRead.o \
    $(BUILD_DIR)/asm/text/mv_THPVideoDecode.o \
    $(BUILD_DIR)/asm/text/mv_movie_player.o \
    $(BUILD_DIR)/asm/text/ph_container.o \
    $(BUILD_DIR)/asm/text/ph_2ndary_container.o \
    $(BUILD_DIR)/asm/text/ph_2ndary_constraint.o \
    $(BUILD_DIR)/asm/text/ph_2ndary_world.o \
    $(BUILD_DIR)/asm/text/ph_2ndary_controller.o \
    $(BUILD_DIR)/asm/text/ph_shape.o \
    $(BUILD_DIR)/asm/text/ph_capsule_shape.o \
    $(BUILD_DIR)/asm/text/ph_ik_solver.o \
    $(BUILD_DIR)/asm/text/ph_ik_controller.o \
    $(BUILD_DIR)/asm/text/ph_ik_two_joint_solver.o \
    $(BUILD_DIR)/asm/text/ph_actor.o \
    $(BUILD_DIR)/asm/text/ph_world.o \
    $(BUILD_DIR)/asm/text/ph_Interface.o \
    $(BUILD_DIR)/asm/text/ph_math.o \
    $(BUILD_DIR)/asm/text/cm_camera_controller.o \
    $(BUILD_DIR)/asm/text/cm_quake.o \
    $(BUILD_DIR)/asm/text/cm_replay.o \
    $(BUILD_DIR)/asm/text/cm_subject.o \
    $(BUILD_DIR)/asm/text/cm_controller_default.o \
    $(BUILD_DIR)/asm/text/cm_controller_ai.o \
    $(BUILD_DIR)/asm/text/cm_controller_ai_param.o \
    $(BUILD_DIR)/asm/text/cm_controller_ftarget.o \
    $(BUILD_DIR)/asm/text/cm_controller_adv.o \
    $(BUILD_DIR)/asm/text/cm_controller_adv_free.o \
    $(BUILD_DIR)/asm/text/cm_controller_anm.o \
    $(BUILD_DIR)/asm/text/cm_controller_menu.o \
    $(BUILD_DIR)/asm/text/cm_controller_menu_fixed.o \
    $(BUILD_DIR)/asm/text/cm_controller_photo.o \
    $(BUILD_DIR)/asm/text/cm_controller_fig_disp1.o \
    $(BUILD_DIR)/asm/text/cm_controller_tech.o \
    $(BUILD_DIR)/asm/text/cm_controller_melee_fixed.o \
    $(BUILD_DIR)/asm/text/cm_controller_demo.o \
    $(BUILD_DIR)/asm/text/cm_stage_param.o \
    $(BUILD_DIR)/asm/text/ty_fig_listmng.o \
    $(BUILD_DIR)/asm/text/menu.o \
    $(BUILD_DIR)/asm/text/ty_seal_listmng.o \
    $(BUILD_DIR)/asm/text/mu_menuroot.o \
    $(BUILD_DIR)/asm/text/mu_object.o \
    $(BUILD_DIR)/asm/text/mu_msg.o \
    $(BUILD_DIR)/asm/text/mu_controller.o \
    $(BUILD_DIR)/asm/text/mu_clear_get_mng.o \
    $(BUILD_DIR)/asm/text/mu_clear_get_task.o \
    $(BUILD_DIR)/asm/text/mu_notice_wnd.o \
    $(BUILD_DIR)/asm/text/mu_prize_wnd.o \
    $(BUILD_DIR)/asm/text/mu_collection.o \
    $(BUILD_DIR)/asm/text/mu_wifi_interface.o \
    $(BUILD_DIR)/asm/text/mu_wifi_cnt_wnd.o \
    $(BUILD_DIR)/asm/text/mu_wifi_data_load.o \
    $(BUILD_DIR)/asm/text/if_common.o \
    $(BUILD_DIR)/asm/text/if_mngr.o \
    $(BUILD_DIR)/asm/text/if_center.o \
    $(BUILD_DIR)/asm/text/if_player.o \
    $(BUILD_DIR)/asm/text/if_vsresult.o \
    $(BUILD_DIR)/asm/text/if_simple_result.o \
    $(BUILD_DIR)/asm/text/if_photo.o \
    $(BUILD_DIR)/asm/text/if_snap_save.o \
    $(BUILD_DIR)/asm/text/if_utility.o \
    $(BUILD_DIR)/asm/text/if_reward_list.o \
    $(BUILD_DIR)/asm/text/if_wifi_intr_menu.o \
    $(BUILD_DIR)/asm/text/if_wifipr_mngr.o \
    $(BUILD_DIR)/asm/text/if_wifipr_task.o \
    $(BUILD_DIR)/asm/text/if_wifipr_center.o \
    $(BUILD_DIR)/asm/text/if_wifipr_player.o \
    $(BUILD_DIR)/asm/text/if_minigame_homerun.o \
    $(BUILD_DIR)/asm/text/if_minigame_coin_shooter.o \
    $(BUILD_DIR)/asm/text/if_minigame_training.o \
    $(BUILD_DIR)/asm/text/if_figure_loader.o \
    $(BUILD_DIR)/asm/text/if_adv_mngr.o \
    $(BUILD_DIR)/asm/text/if_adv_task.o \
    $(BUILD_DIR)/asm/text/if_adv_zako.o \
    $(BUILD_DIR)/asm/text/if_adv_boss.o \
    $(BUILD_DIR)/asm/text/if_adv_pause.o \
    $(BUILD_DIR)/asm/text/if_adv_gauge.o \
    $(BUILD_DIR)/asm/text/if_adv_radar.o \
    $(BUILD_DIR)/asm/text/if_stgedit.o \
    $(BUILD_DIR)/asm/text/if_stgedit_mngr.o \
    $(BUILD_DIR)/asm/text/st_global_utility.o \
    $(BUILD_DIR)/asm/text/gr_collision_data.o \
    $(BUILD_DIR)/asm/text/gr_collision.o \
    $(BUILD_DIR)/asm/text/gr_collision_handle.o \
    $(BUILD_DIR)/asm/text/gr_collision_manager.o \
    $(BUILD_DIR)/asm/text/gr_collision_joint.o \
    $(BUILD_DIR)/asm/text/gr_collision_linework.o \
    $(BUILD_DIR)/asm/text/gr_collision_collection.o \
    $(BUILD_DIR)/asm/text/gr_collision_test.o \
    $(BUILD_DIR)/asm/text/gr_collision_test_rhombus.o \
    $(BUILD_DIR)/asm/text/gr_collision_test_circle.o \
    $(BUILD_DIR)/asm/text/gr_collision_shape_rhombus.o \
    $(BUILD_DIR)/asm/text/gr_collision_shape_circle.o \
    $(BUILD_DIR)/asm/text/gr_collision_status.o \
    $(BUILD_DIR)/asm/text/gr_collision_raycheck.o \
    $(BUILD_DIR)/asm/text/gr_collconv.o \
    $(BUILD_DIR)/asm/text/gr_path.o \
    $(BUILD_DIR)/asm/text/ac_cmd_interpreter.o \
    $(BUILD_DIR)/asm/text/ac_anim_cmd_impl.o \
    $(BUILD_DIR)/asm/text/ac_null.o \
    $(BUILD_DIR)/asm/text/ft_system.o \
    $(BUILD_DIR)/asm/text/nt_report.o \
    $(BUILD_DIR)/asm/text/nt_send.o \
    $(BUILD_DIR)/asm/text/nt_sync.o \
    $(BUILD_DIR)/asm/text/nt_tr.o \
    $(BUILD_DIR)/asm/text/network.o \
    $(BUILD_DIR)/asm/text/nt_base.o \
    $(BUILD_DIR)/asm/text/nt_match.o \
    $(BUILD_DIR)/asm/text/nt_offline.o \
    $(BUILD_DIR)/asm/text/nt_friendinfo.o \
    $(BUILD_DIR)/asm/text/d_net_connect.o \
    $(BUILD_DIR)/asm/text/nt_etc_nwc24.o \
    $(BUILD_DIR)/asm/text/nt_etc_xchg.o \
    $(BUILD_DIR)/asm/text/nt_etc_global.o \
    $(BUILD_DIR)/asm/text/nt_etc_dwc.o \
    $(BUILD_DIR)/asm/text/nt_etc_so.o \
    $(BUILD_DIR)/asm/text/nt_etc_nd.o \
    $(BUILD_DIR)/asm/text/nt_etc_sbs.o \
    $(BUILD_DIR)/asm/text/nt_etc_contribution.o \
    $(BUILD_DIR)/asm/text/nt_etc_file.o \
    $(BUILD_DIR)/asm/text/nt_etc_watching.o \
    $(BUILD_DIR)/asm/text/nt_etc_checkdata.o \
    $(BUILD_DIR)/asm/text/nt_etc_boottask.o \
    $(BUILD_DIR)/asm/text/nt_etc_upload_eval.o \
    $(BUILD_DIR)/asm/text/ad_keep_manager.o \
    $(BUILD_DIR)/asm/text/ad_static_data.o \
    $(BUILD_DIR)/asm/text/ad_seal_info.o \
    $(BUILD_DIR)/asm/text/ad_autosave.o \
    $(BUILD_DIR)/asm/text/st_data_container.o \
    $(BUILD_DIR)/asm/text/st_data_container_multi.o \
    $(BUILD_DIR)/asm/text/ut_list__4456.o \
    $(BUILD_DIR)/asm/text/ut_LinkList.o \
    $(BUILD_DIR)/asm/text/ut_binaryFileFormat.o \
    $(BUILD_DIR)/asm/text/ut_CharStrmReader.o \
    $(BUILD_DIR)/asm/text/ut_IOStream.o \
    $(BUILD_DIR)/asm/text/ut_FileStream.o \
    $(BUILD_DIR)/asm/text/ut_DvdFileStream.o \
    $(BUILD_DIR)/asm/text/ut_DvdLockedFileStream.o \
    $(BUILD_DIR)/asm/text/ut_LockedCache.o \
    $(BUILD_DIR)/asm/text/ut_Font.o \
    $(BUILD_DIR)/asm/text/ut_RomFont.o \
    $(BUILD_DIR)/asm/text/ut_ResFontBase.o \
    $(BUILD_DIR)/asm/text/ut_ResFont.o \
    $(BUILD_DIR)/asm/text/ut_CharWriter.o \
    $(BUILD_DIR)/asm/text/math_arithmetic.o \
    $(BUILD_DIR)/asm/text/math_triangular.o \
    $(BUILD_DIR)/asm/text/math_geometry.o \
    $(BUILD_DIR)/asm/text/ef_draworder.o \
    $(BUILD_DIR)/asm/text/ef_effect.o \
    $(BUILD_DIR)/asm/text/ef_effectsystem.o \
    $(BUILD_DIR)/asm/text/ef_emitter.o \
    $(BUILD_DIR)/asm/text/ef_animcurve.o \
    $(BUILD_DIR)/asm/text/ef_particle__4709.o \
    $(BUILD_DIR)/asm/text/ef_resource.o \
    $(BUILD_DIR)/asm/text/ef_util.o \
    $(BUILD_DIR)/asm/text/ef_handle.o \
    $(BUILD_DIR)/asm/text/ef_emitterform.o \
    $(BUILD_DIR)/asm/text/ef_creationqueue.o \
    $(BUILD_DIR)/asm/text/ef_emform.o \
    $(BUILD_DIR)/asm/text/ef_point.o \
    $(BUILD_DIR)/asm/text/ef_line.o \
    $(BUILD_DIR)/asm/text/ef_disc.o \
    $(BUILD_DIR)/asm/text/ef_sphere.o \
    $(BUILD_DIR)/asm/text/ef_cylinder.o \
    $(BUILD_DIR)/asm/text/ef_torus.o \
    $(BUILD_DIR)/asm/text/ef_cube.o \
    $(BUILD_DIR)/asm/text/ef_drawstrategybuilder.o \
    $(BUILD_DIR)/asm/text/ef_drawstrategyimpl.o \
    $(BUILD_DIR)/asm/text/ef_drawbillboardstrategy.o \
    $(BUILD_DIR)/asm/text/ef_drawfreestrategy.o \
    $(BUILD_DIR)/asm/text/ef_drawlinestrategy.o \
    $(BUILD_DIR)/asm/text/ef_drawpointstrategy.o \
    $(BUILD_DIR)/asm/text/ef_drawstripestrategy.o \
    $(BUILD_DIR)/asm/text/lyt_pane.o \
    $(BUILD_DIR)/asm/text/lyt_group.o \
    $(BUILD_DIR)/asm/text/lyt_layout.o \
    $(BUILD_DIR)/asm/text/lyt_picture.o \
    $(BUILD_DIR)/asm/text/lyt_textBox.o \
    $(BUILD_DIR)/asm/text/lyt_window.o \
    $(BUILD_DIR)/asm/text/lyt_bounding.o \
    $(BUILD_DIR)/asm/text/lyt_material.o \
    $(BUILD_DIR)/asm/text/lyt_texMap.o \
    $(BUILD_DIR)/asm/text/lyt_drawInfo.o \
    $(BUILD_DIR)/asm/text/lyt_animation.o \
    $(BUILD_DIR)/asm/text/lyt_resourceAccessor.o \
    $(BUILD_DIR)/asm/text/lyt_arcResourceAccessor.o \
    $(BUILD_DIR)/asm/text/lyt_common.o \
    $(BUILD_DIR)/asm/text/g3d_rescommon.o \
    $(BUILD_DIR)/asm/text/g3d_resdict.o \
    $(BUILD_DIR)/asm/text/g3d_resfile.o \
    $(BUILD_DIR)/asm/text/g3d_resmdl.o \
    $(BUILD_DIR)/asm/text/g3d_resshp.o \
    $(BUILD_DIR)/asm/text/g3d_restev.o \
    $(BUILD_DIR)/asm/text/g3d_resmat.o \
    $(BUILD_DIR)/asm/text/g3d_resvtx.o \
    $(BUILD_DIR)/asm/text/g3d_restex.o \
    $(BUILD_DIR)/asm/text/g3d_resnode.o \
    $(BUILD_DIR)/asm/text/g3d_resanm.o \
    $(BUILD_DIR)/asm/text/g3d_resanmvis.o \
    $(BUILD_DIR)/asm/text/g3d_resanmclr.o \
    $(BUILD_DIR)/asm/text/g3d_resanmtexpat.o \
    $(BUILD_DIR)/asm/text/g3d_resanmtexsrt.o \
    $(BUILD_DIR)/asm/text/g3d_resanmchr.o \
    $(BUILD_DIR)/asm/text/g3d_reslightset.o \
    $(BUILD_DIR)/asm/text/g3d_resanmamblight.o \
    $(BUILD_DIR)/asm/text/g3d_resanmlight.o \
    $(BUILD_DIR)/asm/text/g3d_resanmfog.o \
    $(BUILD_DIR)/asm/text/g3d_resanmcamera.o \
    $(BUILD_DIR)/asm/text/g3d_resanmscn.o \
    $(BUILD_DIR)/asm/text/g3d_resanmshp.o \
    $(BUILD_DIR)/asm/text/g3d_anmvis.o \
    $(BUILD_DIR)/asm/text/g3d_anmclr.o \
    $(BUILD_DIR)/asm/text/g3d_anmtexpat.o \
    $(BUILD_DIR)/asm/text/g3d_anmtexsrt.o \
    $(BUILD_DIR)/asm/text/g3d_anmchr.o \
    $(BUILD_DIR)/asm/text/g3d_anmshp.o \
    $(BUILD_DIR)/asm/text/g3d_anmscn.o \
    $(BUILD_DIR)/asm/text/g3d_obj.o \
    $(BUILD_DIR)/asm/text/g3d_anmobj.o \
    $(BUILD_DIR)/asm/text/g3d_gpu.o \
    $(BUILD_DIR)/asm/text/g3d_cpu.o \
    $(BUILD_DIR)/asm/text/g3d_state.o \
    $(BUILD_DIR)/asm/text/g3d_draw1mat1shp.o \
    $(BUILD_DIR)/asm/text/g3d_calcview.o \
    $(BUILD_DIR)/asm/text/g3d_dcc.o \
    $(BUILD_DIR)/asm/text/g3d_workmem.o \
    $(BUILD_DIR)/asm/text/g3d_calcworld.o \
    $(BUILD_DIR)/asm/text/g3d_draw.o \
    $(BUILD_DIR)/asm/text/g3d_camera.o \
    $(BUILD_DIR)/asm/text/g3d_basic.o \
    $(BUILD_DIR)/asm/text/g3d_maya.o \
    $(BUILD_DIR)/asm/text/g3d_xsi.o \
    $(BUILD_DIR)/asm/text/g3d_3dsmax.o \
    $(BUILD_DIR)/asm/text/g3d_scnobj.o \
    $(BUILD_DIR)/asm/text/g3d_scnroot.o \
    $(BUILD_DIR)/asm/text/g3d_scnmdlsmpl.o \
    $(BUILD_DIR)/asm/text/g3d_scnmdl.o \
    $(BUILD_DIR)/asm/text/g3d_scnchoice.o \
    $(BUILD_DIR)/asm/text/g3d_scnmdlexpand.o \
    $(BUILD_DIR)/asm/text/g3d_calcmaterial.o \
    $(BUILD_DIR)/asm/text/g3d_init.o \
    $(BUILD_DIR)/asm/text/g3d_scnproc.o \
    $(BUILD_DIR)/asm/text/g3d_fog.o \
    $(BUILD_DIR)/asm/text/g3d_light.o \
    $(BUILD_DIR)/asm/text/g3d_calcvtx.o \
    $(BUILD_DIR)/asm/text/snd_AxManager.o \
    $(BUILD_DIR)/asm/text/snd_AxVoice.o \
    $(BUILD_DIR)/asm/text/snd_AxVoiceManager.o \
    $(BUILD_DIR)/asm/text/snd_AxfxImpl.o \
    $(BUILD_DIR)/asm/text/snd_Bank.o \
    $(BUILD_DIR)/asm/text/snd_BankFile.o \
    $(BUILD_DIR)/asm/text/snd_BasicPlayer.o \
    $(BUILD_DIR)/asm/text/snd_BasicSound.o \
    $(BUILD_DIR)/asm/text/snd_Channel.o \
    $(BUILD_DIR)/asm/text/snd_DisposeCallbackManager.o \
    $(BUILD_DIR)/asm/text/snd_DvdSoundArchive.o \
    $(BUILD_DIR)/asm/text/snd_EnvGenerator.o \
    $(BUILD_DIR)/asm/text/snd_ExternalSoundPlayer.o \
    $(BUILD_DIR)/asm/text/snd_FrameHeap.o \
    $(BUILD_DIR)/asm/text/snd_FxDelay.o \
    $(BUILD_DIR)/asm/text/snd_FxReverbHi.o \
    $(BUILD_DIR)/asm/text/snd_InstancePool.o \
    $(BUILD_DIR)/asm/text/snd_Lfo.o \
    $(BUILD_DIR)/asm/text/snd_MemorySoundArchive.o \
    $(BUILD_DIR)/asm/text/snd_MidiSeqPlayer.o \
    $(BUILD_DIR)/asm/text/snd_MmlParser.o \
    $(BUILD_DIR)/asm/text/snd_MmlSeqTrack.o \
    $(BUILD_DIR)/asm/text/snd_MmlSeqTrackAllocator.o \
    $(BUILD_DIR)/asm/text/snd_NandSoundArchive.o \
    $(BUILD_DIR)/asm/text/snd_RemoteSpeaker.o \
    $(BUILD_DIR)/asm/text/snd_RemoteSpeakerManager.o \
    $(BUILD_DIR)/asm/text/snd_SeqFile.o \
    $(BUILD_DIR)/asm/text/snd_SeqPlayer.o \
    $(BUILD_DIR)/asm/text/snd_SeqSound.o \
    $(BUILD_DIR)/asm/text/snd_SeqSoundHandle.o \
    $(BUILD_DIR)/asm/text/snd_SeqTrack.o \
    $(BUILD_DIR)/asm/text/snd_Sound3DActor.o \
    $(BUILD_DIR)/asm/text/snd_Sound3DListener.o \
    $(BUILD_DIR)/asm/text/snd_Sound3DManager.o \
    $(BUILD_DIR)/asm/text/snd_SoundActor.o \
    $(BUILD_DIR)/asm/text/snd_SoundArchive.o \
    $(BUILD_DIR)/asm/text/snd_SoundArchiveFile.o \
    $(BUILD_DIR)/asm/text/snd_SoundArchiveLoader.o \
    $(BUILD_DIR)/asm/text/snd_SoundArchivePlayer.o \
    $(BUILD_DIR)/asm/text/snd_SoundHandle.o \
    $(BUILD_DIR)/asm/text/snd_SoundHeap.o \
    $(BUILD_DIR)/asm/text/snd_SoundPlayer.o \
    $(BUILD_DIR)/asm/text/snd_SoundStartable.o \
    $(BUILD_DIR)/asm/text/snd_SoundSystem.o \
    $(BUILD_DIR)/asm/text/snd_SoundThread.o \
    $(BUILD_DIR)/asm/text/snd_StrmChannel.o \
    $(BUILD_DIR)/asm/text/snd_StrmFile.o \
    $(BUILD_DIR)/asm/text/snd_StrmPlayer.o \
    $(BUILD_DIR)/asm/text/snd_StrmSound.o \
    $(BUILD_DIR)/asm/text/snd_StrmSoundHandle.o \
    $(BUILD_DIR)/asm/text/snd_Task.o \
    $(BUILD_DIR)/asm/text/snd_TaskManager.o \
    $(BUILD_DIR)/asm/text/snd_TaskThread.o \
    $(BUILD_DIR)/asm/text/snd_Voice.o \
    $(BUILD_DIR)/asm/text/snd_VoiceManager.o \
    $(BUILD_DIR)/asm/text/snd_Util.o \
    $(BUILD_DIR)/asm/text/snd_WaveFile.o \
    $(BUILD_DIR)/asm/text/snd_WaveSound.o \
    $(BUILD_DIR)/asm/text/snd_WaveSoundHandle.o \
    $(BUILD_DIR)/asm/text/snd_WsdFile.o \
    $(BUILD_DIR)/asm/text/snd_WsdPlayer.o \
    $(BUILD_DIR)/asm/text/snd_adpcm.o \
    $(BUILD_DIR)/asm/text/PPCArch.o \
    $(BUILD_DIR)/asm/text/OS.o \
    $(BUILD_DIR)/asm/text/OSAlarm.o \
    $(BUILD_DIR)/asm/text/OSAlloc.o \
    $(BUILD_DIR)/asm/text/OSArena.o \
    $(BUILD_DIR)/asm/text/OSAudioSystem.o \
    $(BUILD_DIR)/asm/text/OSCache.o \
    $(BUILD_DIR)/asm/text/OSContext.o \
    $(BUILD_DIR)/asm/text/OSError.o \
    $(BUILD_DIR)/asm/text/OSExec.o \
    $(BUILD_DIR)/asm/text/OSFatal.o \
    $(BUILD_DIR)/asm/text/OSFont.o \
    $(BUILD_DIR)/asm/text/OSInterrupt.o \
    $(BUILD_DIR)/asm/text/OSLink.o \
    $(BUILD_DIR)/asm/text/OSMessage.o \
    $(BUILD_DIR)/asm/text/OSMemory.o \
    $(BUILD_DIR)/asm/text/OSMutex.o \
    $(BUILD_DIR)/asm/text/OSReboot.o \
    $(BUILD_DIR)/asm/text/OSReset.o \
    $(BUILD_DIR)/asm/text/OSRtc.o \
    $(BUILD_DIR)/asm/text/OSSemaphore.o \
    $(BUILD_DIR)/asm/text/OSSync.o \
    $(BUILD_DIR)/asm/text/OSThread.o \
    $(BUILD_DIR)/asm/text/OSTime.o \
    $(BUILD_DIR)/asm/text/OSUtf.o \
    $(BUILD_DIR)/asm/text/OSIpc.o \
    $(BUILD_DIR)/asm/text/OSStateTM.o \
    $(BUILD_DIR)/asm/text/OSPlayRecord.o \
    $(BUILD_DIR)/asm/text/OSStateFlags.o \
    $(BUILD_DIR)/asm/text/OSNet.o \
    $(BUILD_DIR)/asm/text/OSNandbootInfo.o \
    $(BUILD_DIR)/asm/text/OSPlayTime.o \
    $(BUILD_DIR)/asm/text/__ppc_eabi_init.o \
    $(BUILD_DIR)/asm/text/EXIBios.o \
    $(BUILD_DIR)/asm/text/EXIUart.o \
    $(BUILD_DIR)/asm/text/EXICommon.o \
    $(BUILD_DIR)/asm/text/SIBios.o \
    $(BUILD_DIR)/asm/text/SISamplingRate.o \
    $(BUILD_DIR)/asm/text/db.o \
    $(BUILD_DIR)/asm/text/vi.o \
    $(BUILD_DIR)/asm/text/i2c.o \
    $(BUILD_DIR)/asm/text/vi3in1.o \
    $(BUILD_DIR)/asm/text/mtx.o \
    $(BUILD_DIR)/asm/text/mtxvec.o \
    $(BUILD_DIR)/asm/text/mtx44.o \
    $(BUILD_DIR)/asm/text/vec.o \
    $(BUILD_DIR)/asm/text/quat.o \
    $(BUILD_DIR)/asm/text/GXInit.o \
    $(BUILD_DIR)/asm/text/GXFifo.o \
    $(BUILD_DIR)/asm/text/GXAttr.o \
    $(BUILD_DIR)/asm/text/GXMisc.o \
    $(BUILD_DIR)/asm/text/GXGeometry.o \
    $(BUILD_DIR)/asm/text/GXFrameBuf.o \
    $(BUILD_DIR)/asm/text/GXLight.o \
    $(BUILD_DIR)/asm/text/GXTexture.o \
    $(BUILD_DIR)/asm/text/GXBump.o \
    $(BUILD_DIR)/asm/text/GXTev.o \
    $(BUILD_DIR)/asm/text/GXPixel.o \
    $(BUILD_DIR)/asm/text/GXDraw.o \
    $(BUILD_DIR)/asm/text/GXDisplayList.o \
    $(BUILD_DIR)/asm/text/GXTransform.o \
    $(BUILD_DIR)/asm/text/GXPerf.o \
    $(BUILD_DIR)/asm/text/dvdfs.o \
    $(BUILD_DIR)/asm/text/dvd.o \
    $(BUILD_DIR)/asm/text/dvdqueue.o \
    $(BUILD_DIR)/asm/text/dvderror.o \
    $(BUILD_DIR)/asm/text/dvdidutils.o \
    $(BUILD_DIR)/asm/text/dvdFatal.o \
    $(BUILD_DIR)/asm/text/dvdDeviceError.o \
    $(BUILD_DIR)/asm/text/dvd_broadway.o \
    $(BUILD_DIR)/asm/text/ai.o \
    $(BUILD_DIR)/asm/text/AX.o \
    $(BUILD_DIR)/asm/text/AXAlloc.o \
    $(BUILD_DIR)/asm/text/AXAux.o \
    $(BUILD_DIR)/asm/text/AXCL.o \
    $(BUILD_DIR)/asm/text/AXOut.o \
    $(BUILD_DIR)/asm/text/AXSPB.o \
    $(BUILD_DIR)/asm/text/AXVPB.o \
    $(BUILD_DIR)/asm/text/AXProf.o \
    $(BUILD_DIR)/asm/text/AXFXReverbHi.o \
    $(BUILD_DIR)/asm/text/AXFXReverbHiExp.o \
    $(BUILD_DIR)/asm/text/AXFXDelay.o \
    $(BUILD_DIR)/asm/text/AXFXHooks.o \
    $(BUILD_DIR)/asm/text/mem_heapCommon.o \
    $(BUILD_DIR)/asm/text/mem_expHeap.o \
    $(BUILD_DIR)/asm/text/mem_frameHeap.o \
    $(BUILD_DIR)/asm/text/mem_allocator.o \
    $(BUILD_DIR)/asm/text/mem_list.o \
    $(BUILD_DIR)/asm/text/CXCompression.o \
    $(BUILD_DIR)/asm/text/CXStreamingUncompression.o \
    $(BUILD_DIR)/asm/text/CXUncompression.o \
    $(BUILD_DIR)/asm/text/CXSecureUncompression.o \
    $(BUILD_DIR)/asm/text/mix.o \
    $(BUILD_DIR)/asm/text/remote.o \
    $(BUILD_DIR)/asm/text/dsp.o \
    $(BUILD_DIR)/asm/text/dsp_debug.o \
    $(BUILD_DIR)/asm/text/dsp_task.o \
    $(BUILD_DIR)/asm/text/nand.o \
    $(BUILD_DIR)/asm/text/NANDOpenClose.o \
    $(BUILD_DIR)/asm/text/encunicode.o \
    $(BUILD_DIR)/asm/text/NANDCore.o \
    $(BUILD_DIR)/asm/text/NANDSecret.o \
    $(BUILD_DIR)/asm/text/NANDCheck.o \
    $(BUILD_DIR)/asm/text/NANDLogging.o \
    $(BUILD_DIR)/asm/text/scsystem.o \
    $(BUILD_DIR)/asm/text/scapi.o \
    $(BUILD_DIR)/asm/text/scapi_prdinfo.o \
    $(BUILD_DIR)/asm/text/wenc.o \
    $(BUILD_DIR)/asm/text/arc.o \
    $(BUILD_DIR)/asm/text/esp.o \
    $(BUILD_DIR)/asm/text/ipcMain.o \
    $(BUILD_DIR)/asm/text/ipcclt.o \
    $(BUILD_DIR)/asm/text/encutility.o \
    $(BUILD_DIR)/asm/text/memory.o \
    $(BUILD_DIR)/asm/text/ipcProfile.o \
    $(BUILD_DIR)/asm/text/fs.o \
    $(BUILD_DIR)/asm/text/Pad.o \
    $(BUILD_DIR)/asm/text/WPAD.o \
    $(BUILD_DIR)/asm/text/WPADHIDParser.o \
    $(BUILD_DIR)/asm/text/WPADEncrypt.o \
    $(BUILD_DIR)/asm/text/WPADMem.o \
    $(BUILD_DIR)/asm/text/debug_msg.o \
    $(BUILD_DIR)/asm/text/KPAD.o \
    $(BUILD_DIR)/asm/text/euart.o \
    $(BUILD_DIR)/asm/text/usb.o \
    $(BUILD_DIR)/asm/text/WUD.o \
    $(BUILD_DIR)/asm/text/WUDHidHost.o \
    $(BUILD_DIR)/asm/text/debug_msg__8006.o \
    $(BUILD_DIR)/asm/text/gki_buffer.o \
    $(BUILD_DIR)/asm/text/gki_time.o \
    $(BUILD_DIR)/asm/text/gki_ppc.o \
    $(BUILD_DIR)/asm/text/hcisu_h2.o \
    $(BUILD_DIR)/asm/text/uusb_ppc.o \
    $(BUILD_DIR)/asm/text/bte_hcisu.o \
    $(BUILD_DIR)/asm/text/bte_init.o \
    $(BUILD_DIR)/asm/text/bte_logmsg.o \
    $(BUILD_DIR)/asm/text/bte_main.o \
    $(BUILD_DIR)/asm/text/btu_task1.o \
    $(BUILD_DIR)/asm/text/bd.o \
    $(BUILD_DIR)/asm/text/bta_sys_conn.o \
    $(BUILD_DIR)/asm/text/bta_sys_main.o \
    $(BUILD_DIR)/asm/text/ptim.o \
    $(BUILD_DIR)/asm/text/utl.o \
    $(BUILD_DIR)/asm/text/bta_dm_act.o \
    $(BUILD_DIR)/asm/text/bta_dm_api.o \
    $(BUILD_DIR)/asm/text/bta_dm_main.o \
    $(BUILD_DIR)/asm/text/bta_dm_pm.o \
    $(BUILD_DIR)/asm/text/bta_hh_act.o \
    $(BUILD_DIR)/asm/text/bta_hh_api.o \
    $(BUILD_DIR)/asm/text/bta_hh_main.o \
    $(BUILD_DIR)/asm/text/bta_hh_utils.o \
    $(BUILD_DIR)/asm/text/btm_acl.o \
    $(BUILD_DIR)/asm/text/btm_dev.o \
    $(BUILD_DIR)/asm/text/btm_devctl.o \
    $(BUILD_DIR)/asm/text/btm_discovery.o \
    $(BUILD_DIR)/asm/text/btm_inq.o \
    $(BUILD_DIR)/asm/text/btm_main.o \
    $(BUILD_DIR)/asm/text/btm_pm.o \
    $(BUILD_DIR)/asm/text/btm_sco.o \
    $(BUILD_DIR)/asm/text/btm_sec.o \
    $(BUILD_DIR)/asm/text/btu_hcif.o \
    $(BUILD_DIR)/asm/text/btu_init.o \
    $(BUILD_DIR)/asm/text/wbt_ext.o \
    $(BUILD_DIR)/asm/text/gap_api.o \
    $(BUILD_DIR)/asm/text/gap_conn.o \
    $(BUILD_DIR)/asm/text/gap_utils.o \
    $(BUILD_DIR)/asm/text/hcicmds.o \
    $(BUILD_DIR)/asm/text/hidd_api.o \
    $(BUILD_DIR)/asm/text/hidd_conn.o \
    $(BUILD_DIR)/asm/text/hidd_mgmt.o \
    $(BUILD_DIR)/asm/text/hidd_pm.o \
    $(BUILD_DIR)/asm/text/hidh_api.o \
    $(BUILD_DIR)/asm/text/hidh_conn.o \
    $(BUILD_DIR)/asm/text/l2c_api.o \
    $(BUILD_DIR)/asm/text/l2c_csm.o \
    $(BUILD_DIR)/asm/text/l2c_link.o \
    $(BUILD_DIR)/asm/text/l2c_main.o \
    $(BUILD_DIR)/asm/text/l2c_utils.o \
    $(BUILD_DIR)/asm/text/port_api.o \
    $(BUILD_DIR)/asm/text/port_rfc.o \
    $(BUILD_DIR)/asm/text/port_utils.o \
    $(BUILD_DIR)/asm/text/rfc_l2cap_if.o \
    $(BUILD_DIR)/asm/text/rfc_mx_fsm.o \
    $(BUILD_DIR)/asm/text/rfc_port_fsm.o \
    $(BUILD_DIR)/asm/text/rfc_port_if.o \
    $(BUILD_DIR)/asm/text/rfc_ts_frames.o \
    $(BUILD_DIR)/asm/text/rfc_utils.o \
    $(BUILD_DIR)/asm/text/sdp_api.o \
    $(BUILD_DIR)/asm/text/sdp_db.o \
    $(BUILD_DIR)/asm/text/sdp_discovery.o \
    $(BUILD_DIR)/asm/text/sdp_main.o \
    $(BUILD_DIR)/asm/text/sdp_server.o \
    $(BUILD_DIR)/asm/text/sdp_utils.o \
    $(BUILD_DIR)/asm/text/TPL.o \
    $(BUILD_DIR)/asm/text/THPDec.o \
    $(BUILD_DIR)/asm/text/THPAudio.o \
    $(BUILD_DIR)/asm/text/DebuggerDriver.o \
    $(BUILD_DIR)/asm/text/exi2.o \
    $(BUILD_DIR)/asm/text/encapi.o \
    $(BUILD_DIR)/asm/text/decapi.o \
    $(BUILD_DIR)/asm/text/mkhdec3.o \
    $(BUILD_DIR)/asm/text/buffer_system.o \
    $(BUILD_DIR)/asm/text/getcode.o \
    $(BUILD_DIR)/asm/text/idct_block_var.o \
    $(BUILD_DIR)/asm/text/iqdec_b65_frv32.o \
    $(BUILD_DIR)/asm/text/jdec.o \
    $(BUILD_DIR)/asm/text/jpd_main.o \
    $(BUILD_DIR)/asm/text/exif_parse.o \
    $(BUILD_DIR)/asm/text/iqdec_resolution_change_a3.o \
    $(BUILD_DIR)/asm/text/idct_resolution_change_var.o \
    $(BUILD_DIR)/asm/text/Texture_MCUtoRGBA8.o \
    $(BUILD_DIR)/asm/text/Texture_MCUtoRGB565.o \
    $(BUILD_DIR)/asm/text/stream.o \
    $(BUILD_DIR)/asm/text/enc_block_fast.o \
    $(BUILD_DIR)/asm/text/enc_edge_mcu.o \
    $(BUILD_DIR)/asm/text/enc_frm.o \
    $(BUILD_DIR)/asm/text/enc_image.o \
    $(BUILD_DIR)/asm/text/enc_main.o \
    $(BUILD_DIR)/asm/text/enc_mcu.o \
    $(BUILD_DIR)/asm/text/enc_scan.o \
    $(BUILD_DIR)/asm/text/fdct_block_a4.o \
    $(BUILD_DIR)/asm/text/huffman.o \
    $(BUILD_DIR)/asm/text/quant.o \
    $(BUILD_DIR)/asm/text/enc_main_rate_control.o \
    $(BUILD_DIR)/asm/text/enc_block_fast_rate_control.o \
    $(BUILD_DIR)/asm/text/enc_edge_rate_control.o \
    $(BUILD_DIR)/asm/text/Texture_RGBA8toMCU.o \
    $(BUILD_DIR)/asm/text/Texture_RGB565toMCU.o \
    $(BUILD_DIR)/asm/text/HBMBase.o \
    $(BUILD_DIR)/asm/text/HBMAnmController.o \
    $(BUILD_DIR)/asm/text/HBMFrameController.o \
    $(BUILD_DIR)/asm/text/HBMGUIManager.o \
    $(BUILD_DIR)/asm/text/HBMController.o \
    $(BUILD_DIR)/asm/text/HBMRemoteSpk.o \
    $(BUILD_DIR)/asm/text/hkBaseSystem.o \
    $(BUILD_DIR)/asm/text/hkClass.o \
    $(BUILD_DIR)/asm/text/hkClassMember.o \
    $(BUILD_DIR)/asm/text/hkError.o \
    $(BUILD_DIR)/asm/text/hkArray.o \
    $(BUILD_DIR)/asm/text/hkStringMapBase.o \
    $(BUILD_DIR)/asm/text/hkMemory.o \
    $(BUILD_DIR)/asm/text/hkScratchpad.o \
    $(BUILD_DIR)/asm/text/hkStackTracer.o \
    $(BUILD_DIR)/asm/text/hkThreadMemory.o \
    $(BUILD_DIR)/asm/text/hkPoolMemory.o \
    $(BUILD_DIR)/asm/text/hkMonitorStream.o \
    $(BUILD_DIR)/asm/text/hkUnionFind.o \
    $(BUILD_DIR)/asm/text/hkSystemClock.o \
    $(BUILD_DIR)/asm/text/hkIstream.o \
    $(BUILD_DIR)/asm/text/hkOstream.o \
    $(BUILD_DIR)/asm/text/hkStreamReader.o \
    $(BUILD_DIR)/asm/text/hkStreamWriter.o \
    $(BUILD_DIR)/asm/text/hkBufferedStreamReader.o \
    $(BUILD_DIR)/asm/text/hkBufferedStreamWriter.o \
    $(BUILD_DIR)/asm/text/hkString.o \
    $(BUILD_DIR)/asm/text/hkMultiThreadLock.o \
    $(BUILD_DIR)/asm/text/hkMotionState.o \
    $(BUILD_DIR)/asm/text/hkMathTypes.o \
    $(BUILD_DIR)/asm/text/hkMathUtil.o \
    $(BUILD_DIR)/asm/text/hkMatrix3.o \
    $(BUILD_DIR)/asm/text/hkMatrix4.o \
    $(BUILD_DIR)/asm/text/hkMatrix6.o \
    $(BUILD_DIR)/asm/text/hkQuaternion.o \
    $(BUILD_DIR)/asm/text/hkRotation.o \
    $(BUILD_DIR)/asm/text/hkSweptTransform.o \
    $(BUILD_DIR)/asm/text/hkSweptTransformUtil.o \
    $(BUILD_DIR)/asm/text/hkTransform.o \
    $(BUILD_DIR)/asm/text/hkVector4.o \
    $(BUILD_DIR)/asm/text/hk1dBilateralConstraintBuildJacobian.o \
    $(BUILD_DIR)/asm/text/hkInternalConstraintUtils.o \
    $(BUILD_DIR)/asm/text/hkChainBuildJacobian.o \
    $(BUILD_DIR)/asm/text/hkPoweredChainSolverUtil.o \
    $(BUILD_DIR)/asm/text/hkSimpleContactConstraintInfo.o \
    $(BUILD_DIR)/asm/text/hkMotorBuildJacobian.o \
    $(BUILD_DIR)/asm/text/hkSimpleConstraintUtil.o \
    $(BUILD_DIR)/asm/text/hkSolver.o \
    $(BUILD_DIR)/asm/text/hkSolverCheck.o \
    $(BUILD_DIR)/asm/text/hkSolverExport.o \
    $(BUILD_DIR)/asm/text/hkSolverGetToiVelocities.o \
    $(BUILD_DIR)/asm/text/hkSolverTimeDate.o \
    $(BUILD_DIR)/asm/text/hkVehicleFrictionSolver.o \
    $(BUILD_DIR)/asm/text/hkBoxBoxAgent.o \
    $(BUILD_DIR)/asm/text/hkBoxBoxManifold.o \
    $(BUILD_DIR)/asm/text/hkBvAgent.o \
    $(BUILD_DIR)/asm/text/hkBvTreeAgent.o \
    $(BUILD_DIR)/asm/text/hkMoppAgent.o \
    $(BUILD_DIR)/asm/text/hkBvTreeStreamAgent.o \
    $(BUILD_DIR)/asm/text/hkMoppBvTreeStreamAgent.o \
    $(BUILD_DIR)/asm/text/hkCapsuleCapsuleAgent.o \
    $(BUILD_DIR)/asm/text/hkCapsuleTriangleAgent.o \
    $(BUILD_DIR)/asm/text/hkConvexListAgent.o \
    $(BUILD_DIR)/asm/text/hkGskBaseAgent.o \
    $(BUILD_DIR)/asm/text/hkGskfAgent.o \
    $(BUILD_DIR)/asm/text/hkPredGskfAgent.o \
    $(BUILD_DIR)/asm/text/hkHeightFieldAgent.o \
    $(BUILD_DIR)/asm/text/hkCollisionAgent.o \
    $(BUILD_DIR)/asm/text/hkIterativeLinearCastAgent.o \
    $(BUILD_DIR)/asm/text/hkListAgent.o \
    $(BUILD_DIR)/asm/text/hkMultiRayConvexAgent.o \
    $(BUILD_DIR)/asm/text/hkMultiSphereAgent.o \
    $(BUILD_DIR)/asm/text/hkMultiSphereTriangleAgent.o \
    $(BUILD_DIR)/asm/text/hkNullAgent.o \
    $(BUILD_DIR)/asm/text/hkPhantomAgent.o \
    $(BUILD_DIR)/asm/text/hkShapeCollectionAgent.o \
    $(BUILD_DIR)/asm/text/hkSphereBoxAgent.o \
    $(BUILD_DIR)/asm/text/hkSphereCapsuleAgent.o \
    $(BUILD_DIR)/asm/text/hkSphereSphereAgent.o \
    $(BUILD_DIR)/asm/text/hkSphereTriangleAgent.o \
    $(BUILD_DIR)/asm/text/hkSymmetricAgentLinearCast.o \
    $(BUILD_DIR)/asm/text/hkTransformAgent.o \
    $(BUILD_DIR)/asm/text/hkFlagCdBodyPairCollector.o \
    $(BUILD_DIR)/asm/text/hkClosestCdPointCollector.o \
    $(BUILD_DIR)/asm/text/hkSimpleClosestContactCollector.o \
    $(BUILD_DIR)/asm/text/hkAgent3Bridge.o \
    $(BUILD_DIR)/asm/text/hkNullBroadPhaseListener.o \
    $(BUILD_DIR)/asm/text/hkTypedBroadPhaseDispatcher.o \
    $(BUILD_DIR)/asm/text/hkAgentRegisterUtil.o \
    $(BUILD_DIR)/asm/text/hkCollisionDispatcher.o \
    $(BUILD_DIR)/asm/text/hkGroupFilter.o \
    $(BUILD_DIR)/asm/text/hkNullCollisionFilter.o \
    $(BUILD_DIR)/asm/text/hkBoxShape.o \
    $(BUILD_DIR)/asm/text/hkBvShape.o \
    $(BUILD_DIR)/asm/text/hkCapsuleShape.o \
    $(BUILD_DIR)/asm/text/hkShapeCollection.o \
    $(BUILD_DIR)/asm/text/hkConvexShape.o \
    $(BUILD_DIR)/asm/text/hkConvexTranslateShape.o \
    $(BUILD_DIR)/asm/text/hkConvexVerticesShape.o \
    $(BUILD_DIR)/asm/text/hkCylinderShape.o \
    $(BUILD_DIR)/asm/text/hkFastMeshShape.o \
    $(BUILD_DIR)/asm/text/hkShape.o \
    $(BUILD_DIR)/asm/text/hkShapeContainer.o \
    $(BUILD_DIR)/asm/text/hkShapeType.o \
    $(BUILD_DIR)/asm/text/hkMeshShape.o \
    $(BUILD_DIR)/asm/text/hkSphereShape.o \
    $(BUILD_DIR)/asm/text/hkTriangleShape.o \
    $(BUILD_DIR)/asm/text/hkTriangleUtil.o \
    $(BUILD_DIR)/asm/text/hkContactUpdater.o \
    $(BUILD_DIR)/asm/text/hkReportContactMgr.o \
    $(BUILD_DIR)/asm/text/hkSimpleConstraintContactMgr.o \
    $(BUILD_DIR)/asm/text/hkConstraintAtom.o \
    $(BUILD_DIR)/asm/text/hkConstraintAtomUtil.o \
    $(BUILD_DIR)/asm/text/hkBallSocketChainData.o \
    $(BUILD_DIR)/asm/text/hkPoweredChainData.o \
    $(BUILD_DIR)/asm/text/hkGenericConstraintData.o \
    $(BUILD_DIR)/asm/text/hkSimpleContactConstraintData.o \
    $(BUILD_DIR)/asm/text/hkConstraintData.o \
    $(BUILD_DIR)/asm/text/hkConstraintInstance.o \
    $(BUILD_DIR)/asm/text/hkSimpleCollisionResponse.o \
    $(BUILD_DIR)/asm/text/hkConstraintSolverSetup.o \
    $(BUILD_DIR)/asm/text/hkEntity.o \
    $(BUILD_DIR)/asm/text/hkFakeRigidBodyDeactivator.o \
    $(BUILD_DIR)/asm/text/hkRigidBody.o \
    $(BUILD_DIR)/asm/text/hkRigidBodyCinfo.o \
    $(BUILD_DIR)/asm/text/hkSpatialRigidBodyDeactivator.o \
    $(BUILD_DIR)/asm/text/hkEntityCallbackUtil.o \
    $(BUILD_DIR)/asm/text/hkMotion.o \
    $(BUILD_DIR)/asm/text/hkThinBoxMotion.o \
    $(BUILD_DIR)/asm/text/hkBoxMotion.o \
    $(BUILD_DIR)/asm/text/hkFixedRigidMotion.o \
    $(BUILD_DIR)/asm/text/hkKeyframedRigidMotion.o \
    $(BUILD_DIR)/asm/text/hkSphereMotion.o \
    $(BUILD_DIR)/asm/text/hkStabilizedBoxMotion.o \
    $(BUILD_DIR)/asm/text/hkRigidMotionUtil.o \
    $(BUILD_DIR)/asm/text/hkAabbPhantom.o \
    $(BUILD_DIR)/asm/text/hkPhantom.o \
    $(BUILD_DIR)/asm/text/hkPhantomBroadPhaseListener.o \
    $(BUILD_DIR)/asm/text/hkBroadPhaseBorder.o \
    $(BUILD_DIR)/asm/text/hkPhysicsSystem.o \
    $(BUILD_DIR)/asm/text/hkSimulationIsland.o \
    $(BUILD_DIR)/asm/text/hkWorld.o \
    $(BUILD_DIR)/asm/text/hkWorldCinfo.o \
    $(BUILD_DIR)/asm/text/hkWorldObject.o \
    $(BUILD_DIR)/asm/text/hkDefaultWorldMaintenanceMgr.o \
    $(BUILD_DIR)/asm/text/hkSimulation.o \
    $(BUILD_DIR)/asm/text/hkBroadPhaseBorderListener.o \
    $(BUILD_DIR)/asm/text/hkEntityEntityBroadPhaseListener.o \
    $(BUILD_DIR)/asm/text/hkWorldAgentUtil.o \
    $(BUILD_DIR)/asm/text/hkWorldCallbackUtil.o \
    $(BUILD_DIR)/asm/text/hkWorldConstraintUtil.o \
    $(BUILD_DIR)/asm/text/hkWorldOperationQueue.o \
    $(BUILD_DIR)/asm/text/hkWorldOperationUtil.o \
    $(BUILD_DIR)/asm/text/hkBoxBoxAgent3.o \
    $(BUILD_DIR)/asm/text/hkCapsuleTriangleAgent3.o \
    $(BUILD_DIR)/asm/text/hkAgent1nMachine.o \
    $(BUILD_DIR)/asm/text/hkAgentMachineUtil.o \
    $(BUILD_DIR)/asm/text/hkAgentNnMachine.o \
    $(BUILD_DIR)/asm/text/hkPredGskAgent3.o \
    $(BUILD_DIR)/asm/text/hkPredGskCylinderAgent3.o \
    $(BUILD_DIR)/asm/text/hkBoxBoxCollisionDetection.o \
    $(BUILD_DIR)/asm/text/hk3AxisSweep.o \
    $(BUILD_DIR)/asm/text/hkBroadPhase.o \
    $(BUILD_DIR)/asm/text/hkContinuousGsk.o \
    $(BUILD_DIR)/asm/text/hkGskManifoldUtil.o \
    $(BUILD_DIR)/asm/text/hkGsk.o \
    $(BUILD_DIR)/asm/text/hkGskCache.o \
    $(BUILD_DIR)/asm/text/hkConvexPenetrationUtil.o \
    $(BUILD_DIR)/asm/text/hkCvxCvxDistByHeuristicSampling.o \
    $(BUILD_DIR)/asm/text/hkWingedEdge.o \
    $(BUILD_DIR)/asm/text/hkMoppAabbCastVirtualMachine.o \
    $(BUILD_DIR)/asm/text/hkCollideCapsuleUtil.o \
    $(BUILD_DIR)/asm/text/hkCollideTriangleUtil.o \
    $(BUILD_DIR)/asm/text/hkRagdollConstraintData.o \
    $(BUILD_DIR)/asm/text/hkContinuousSimulation.o \
    $(BUILD_DIR)/asm/text/hkDefaultToiResourceMgr.o \
    $(BUILD_DIR)/asm/text/hkGeometryUtility.o \
    $(BUILD_DIR)/asm/text/hkConstrainedSystemFilter.o \
    $(BUILD_DIR)/asm/text/hkInertiaTensorComputer.o \
    $(BUILD_DIR)/asm/text/hkVehicleViewer.o \
    $(BUILD_DIR)/asm/text/hkFootPlacementIkSolver.o \
    $(BUILD_DIR)/asm/text/hkLookAtIkSolver.o \
    $(BUILD_DIR)/asm/text/hkTwoJointsIkSolver.o \
    $(BUILD_DIR)/asm/text/hkPose.o \
    $(BUILD_DIR)/asm/text/hkSkeletonUtils.o \
    $(BUILD_DIR)/asm/text/hkBinaryPackfileReader.o \
    $(BUILD_DIR)/asm/text/hkPackfileSectionHeader.o \
    $(BUILD_DIR)/asm/text/hkPackfileData.o \
    $(BUILD_DIR)/asm/text/hkPackfileReader.o \
    $(BUILD_DIR)/asm/text/hkBuiltinTypeRegistry.o \
    $(BUILD_DIR)/asm/text/hkObjectInspector.o \
    $(BUILD_DIR)/asm/text/hkRootLevelContainer.o \
    $(BUILD_DIR)/asm/text/hkStructureLayout.o \
    $(BUILD_DIR)/asm/text/hkVtableClassRegistry.o \
    $(BUILD_DIR)/asm/text/hkVersionRegistry.o \
    $(BUILD_DIR)/asm/text/hkVersionUtil.o \
    $(BUILD_DIR)/asm/text/dwc_base64.o \
    $(BUILD_DIR)/asm/text/dwc_error.o \
    $(BUILD_DIR)/asm/text/dwc_init.o \
    $(BUILD_DIR)/asm/text/dwc_memfunc.o \
    $(BUILD_DIR)/asm/text/dwc_report.o \
    $(BUILD_DIR)/asm/text/dwc_ghttp.o \
    $(BUILD_DIR)/asm/text/dwc_common.o \
    $(BUILD_DIR)/asm/text/dwc_friend.o \
    $(BUILD_DIR)/asm/text/dwc_login.o \
    $(BUILD_DIR)/asm/text/dwc_main.o \
    $(BUILD_DIR)/asm/text/dwc_match.o \
    $(BUILD_DIR)/asm/text/dwc_transport.o \
    $(BUILD_DIR)/asm/text/dwc_nonport.o \
    $(BUILD_DIR)/asm/text/dwci_np_math.o \
    $(BUILD_DIR)/asm/text/dwc_cfriend.o \
    $(BUILD_DIR)/asm/text/dwc_account.o \
    $(BUILD_DIR)/asm/text/dwc_auth_interface.o \
    $(BUILD_DIR)/asm/text/dwc_encsession.o \
    $(BUILD_DIR)/asm/text/dwc_nastime.o \
    $(BUILD_DIR)/asm/text/dwc_nd.o \
    $(BUILD_DIR)/asm/text/dwci_idToIsoA2.o \
    $(BUILD_DIR)/asm/text/dwci_nd.o \
    $(BUILD_DIR)/asm/text/dwc_svl.o \
    $(BUILD_DIR)/asm/text/sbs.o \
    $(BUILD_DIR)/asm/text/sbs_error.o \
    $(BUILD_DIR)/asm/text/darray.o \
    $(BUILD_DIR)/asm/text/hashtable.o \
    $(BUILD_DIR)/asm/text/md5c.o \
    $(BUILD_DIR)/asm/text/nonport.o \
    $(BUILD_DIR)/asm/text/gsAvailable.o \
    $(BUILD_DIR)/asm/text/gsCore.o \
    $(BUILD_DIR)/asm/text/gsCrypt.o \
    $(BUILD_DIR)/asm/text/gsLargeInt.o \
    $(BUILD_DIR)/asm/text/gsRC4.o \
    $(BUILD_DIR)/asm/text/gsSHA1.o \
    $(BUILD_DIR)/asm/text/gsSoap.o \
    $(BUILD_DIR)/asm/text/gsStringUtil.o \
    $(BUILD_DIR)/asm/text/gsXML.o \
    $(BUILD_DIR)/asm/text/gp.o \
    $(BUILD_DIR)/asm/text/gpi.o \
    $(BUILD_DIR)/asm/text/gpiBuddy.o \
    $(BUILD_DIR)/asm/text/gpiBuffer.o \
    $(BUILD_DIR)/asm/text/gpiCallback.o \
    $(BUILD_DIR)/asm/text/gpiConnect.o \
    $(BUILD_DIR)/asm/text/gpiInfo.o \
    $(BUILD_DIR)/asm/text/gpiOperation.o \
    $(BUILD_DIR)/asm/text/gpiPeer.o \
    $(BUILD_DIR)/asm/text/gpiProfile.o \
    $(BUILD_DIR)/asm/text/gpiSearch.o \
    $(BUILD_DIR)/asm/text/gpiTransfer.o \
    $(BUILD_DIR)/asm/text/gpiUnique.o \
    $(BUILD_DIR)/asm/text/gpiUtility.o \
    $(BUILD_DIR)/asm/text/gt2Auth.o \
    $(BUILD_DIR)/asm/text/gt2Buffer.o \
    $(BUILD_DIR)/asm/text/gt2Callback.o \
    $(BUILD_DIR)/asm/text/gt2Connection.o \
    $(BUILD_DIR)/asm/text/gt2Main.o \
    $(BUILD_DIR)/asm/text/gt2Message.o \
    $(BUILD_DIR)/asm/text/gt2Socket.o \
    $(BUILD_DIR)/asm/text/gt2Utility.o \
    $(BUILD_DIR)/asm/text/qr2.o \
    $(BUILD_DIR)/asm/text/qr2regkeys.o \
    $(BUILD_DIR)/asm/text/ghttpBuffer.o \
    $(BUILD_DIR)/asm/text/ghttpCallbacks.o \
    $(BUILD_DIR)/asm/text/ghttpCommon.o \
    $(BUILD_DIR)/asm/text/ghttpConnection.o \
    $(BUILD_DIR)/asm/text/ghttpEncryption.o \
    $(BUILD_DIR)/asm/text/ghttpMain.o \
    $(BUILD_DIR)/asm/text/ghttpPost.o \
    $(BUILD_DIR)/asm/text/ghttpProcess.o \
    $(BUILD_DIR)/asm/text/gbucket.o \
    $(BUILD_DIR)/asm/text/gstats.o \
    $(BUILD_DIR)/asm/text/NATify.o \
    $(BUILD_DIR)/asm/text/natneg.o \
    $(BUILD_DIR)/asm/text/sb_crypt.o \
    $(BUILD_DIR)/asm/text/sb_queryengine.o \
    $(BUILD_DIR)/asm/text/sb_server.o \
    $(BUILD_DIR)/asm/text/sb_serverbrowsing.o \
    $(BUILD_DIR)/asm/text/sb_serverlist.o \
    $(BUILD_DIR)/asm/text/sakeMain.o \
    $(BUILD_DIR)/asm/text/sakeRequest.o \
    $(BUILD_DIR)/asm/text/sakeRequestModify.o \
    $(BUILD_DIR)/asm/text/ncdsystem.o \
    $(BUILD_DIR)/asm/text/nettime.o \
    $(BUILD_DIR)/asm/text/crc.o \
    $(BUILD_DIR)/asm/text/neterrorcode.o \
    $(BUILD_DIR)/asm/text/NETVersion.o \
    $(BUILD_DIR)/asm/text/crypto.o \
    $(BUILD_DIR)/asm/text/aes.o \
    $(BUILD_DIR)/asm/text/aes_cbc.o \
    $(BUILD_DIR)/asm/text/wireless_macaddr.o \
    $(BUILD_DIR)/asm/text/NHTTP_bgnend.o \
    $(BUILD_DIR)/asm/text/NHTTP_control.o \
    $(BUILD_DIR)/asm/text/NHTTP_list.o \
    $(BUILD_DIR)/asm/text/NHTTP_os_RVL.o \
    $(BUILD_DIR)/asm/text/NHTTP_recvbuf.o \
    $(BUILD_DIR)/asm/text/NHTTP_request.o \
    $(BUILD_DIR)/asm/text/NHTTP_response.o \
    $(BUILD_DIR)/asm/text/NHTTP_socket_RVL.o \
    $(BUILD_DIR)/asm/text/NHTTP_stdlib_RVL.o \
    $(BUILD_DIR)/asm/text/NHTTP_thread.o \
    $(BUILD_DIR)/asm/text/d_nhttp_private.o \
    $(BUILD_DIR)/asm/text/d_nhttp.o \
    $(BUILD_DIR)/asm/text/d_nhttp_common.o \
    $(BUILD_DIR)/asm/text/NWC24StdAPI.o \
    $(BUILD_DIR)/asm/text/NWC24FileAPI.o \
    $(BUILD_DIR)/asm/text/NWC24Config.o \
    $(BUILD_DIR)/asm/text/NWC24Utils.o \
    $(BUILD_DIR)/asm/text/NWC24Manage.o \
    $(BUILD_DIR)/asm/text/NWC24MsgObj.o \
    $(BUILD_DIR)/asm/text/NWC24MBoxCtrl.o \
    $(BUILD_DIR)/asm/text/NWC24Mime.o \
    $(BUILD_DIR)/asm/text/NWC24Parser.o \
    $(BUILD_DIR)/asm/text/NWC24MsgCommit.o \
    $(BUILD_DIR)/asm/text/NWC24MsgRead.o \
    $(BUILD_DIR)/asm/text/NWC24MsgSearch.o \
    $(BUILD_DIR)/asm/text/NWC24Schedule.o \
    $(BUILD_DIR)/asm/text/NWC24DateParser.o \
    $(BUILD_DIR)/asm/text/NWC24FriendList.o \
    $(BUILD_DIR)/asm/text/NWC24SecretFList.o \
    $(BUILD_DIR)/asm/text/NWC24UserId.o \
    $(BUILD_DIR)/asm/text/NWC24Time.o \
    $(BUILD_DIR)/asm/text/NWC24Ipc.o \
    $(BUILD_DIR)/asm/text/NWC24Download.o \
    $(BUILD_DIR)/asm/text/NWC24System.o \
    $(BUILD_DIR)/asm/text/SOCommon.o \
    $(BUILD_DIR)/asm/text/SOBasic.o \
    $(BUILD_DIR)/asm/text/SOInformation.o \
    $(BUILD_DIR)/asm/text/SOOption.o \
    $(BUILD_DIR)/asm/text/ssl_api.o \
    $(BUILD_DIR)/asm/text/ssl_mutex.o \
    $(BUILD_DIR)/asm/text/pf_clib.o \
    $(BUILD_DIR)/asm/text/pf_code.o \
    $(BUILD_DIR)/asm/text/pf_service.o \
    $(BUILD_DIR)/asm/text/pf_str.o \
    $(BUILD_DIR)/asm/text/pf_w_clib.o \
    $(BUILD_DIR)/asm/text/pf_driver.o \
    $(BUILD_DIR)/asm/text/pdm_bpb.o \
    $(BUILD_DIR)/asm/text/pdm_disk.o \
    $(BUILD_DIR)/asm/text/pdm_partition.o \
    $(BUILD_DIR)/asm/text/pdm_mbr.o \
    $(BUILD_DIR)/asm/text/pdm_dskmng.o \
    $(BUILD_DIR)/asm/text/pf_cache.o \
    $(BUILD_DIR)/asm/text/pf_cluster.o \
    $(BUILD_DIR)/asm/text/pf_dir.o \
    $(BUILD_DIR)/asm/text/pf_entry.o \
    $(BUILD_DIR)/asm/text/pf_entry_iterator.o \
    $(BUILD_DIR)/asm/text/pf_fat.o \
    $(BUILD_DIR)/asm/text/pf_fat12.o \
    $(BUILD_DIR)/asm/text/pf_fat16.o \
    $(BUILD_DIR)/asm/text/pf_fat32.o \
    $(BUILD_DIR)/asm/text/pf_fatfs.o \
    $(BUILD_DIR)/asm/text/pf_file.o \
    $(BUILD_DIR)/asm/text/pf_path.o \
    $(BUILD_DIR)/asm/text/pf_sector.o \
    $(BUILD_DIR)/asm/text/pf_volume.o \
    $(BUILD_DIR)/asm/text/pf_cp932.o \
    $(BUILD_DIR)/asm/text/pf_api_util.o \
    $(BUILD_DIR)/asm/text/pf_attach.o \
    $(BUILD_DIR)/asm/text/pf_chdir.o \
    $(BUILD_DIR)/asm/text/pf_create.o \
    $(BUILD_DIR)/asm/text/pf_detach.o \
    $(BUILD_DIR)/asm/text/pf_errnum.o \
    $(BUILD_DIR)/asm/text/pf_fclose.o \
    $(BUILD_DIR)/asm/text/pf_finfo.o \
    $(BUILD_DIR)/asm/text/pf_fopen.o \
    $(BUILD_DIR)/asm/text/pf_format.o \
    $(BUILD_DIR)/asm/text/pf_fread.o \
    $(BUILD_DIR)/asm/text/pf_fseek.o \
    $(BUILD_DIR)/asm/text/pf_fsfirst.o \
    $(BUILD_DIR)/asm/text/pf_fsnext.o \
    $(BUILD_DIR)/asm/text/pf_fstat.o \
    $(BUILD_DIR)/asm/text/pf_fwrite.o \
    $(BUILD_DIR)/asm/text/pf_getdev.o \
    $(BUILD_DIR)/asm/text/pf_init_prfile2.o \
    $(BUILD_DIR)/asm/text/pf_mkdir.o \
    $(BUILD_DIR)/asm/text/pf_remove.o \
    $(BUILD_DIR)/asm/text/pf_unmount.o \
    $(BUILD_DIR)/asm/text/pf_filelock.o \
    $(BUILD_DIR)/asm/text/pf_system.o \
    $(BUILD_DIR)/asm/text/d_vf.o \
    $(BUILD_DIR)/asm/text/d_vf_sys.o \
    $(BUILD_DIR)/asm/text/d_hash.o \
    $(BUILD_DIR)/asm/text/d_time.o \
    $(BUILD_DIR)/asm/text/d_common.o \
    $(BUILD_DIR)/asm/text/nand_drv.o \
    $(BUILD_DIR)/asm/text/sd_drv.o \
    $(BUILD_DIR)/asm/text/sdi_api.o \
    $(BUILD_DIR)/asm/text/RFL_System.o \
    $(BUILD_DIR)/asm/text/RFL_NANDLoader.o \
    $(BUILD_DIR)/asm/text/RFL_NANDAccess.o \
    $(BUILD_DIR)/asm/text/RFL_Model.o \
    $(BUILD_DIR)/asm/text/RFL_HiddenDatabase.o \
    $(BUILD_DIR)/asm/text/RFL_Database.o \
    $(BUILD_DIR)/asm/text/RFL_Controller.o \
    $(BUILD_DIR)/asm/text/RFL_MiddleDatabase.o \
    $(BUILD_DIR)/asm/text/RFL_DefaultDatabase.o \
    $(BUILD_DIR)/asm/text/RFL_DataUtility.o \
    $(BUILD_DIR)/asm/text/RFL_Format.o \
    $(BUILD_DIR)/asm/text/pf_clib__13563.o \
    $(BUILD_DIR)/asm/text/pf_code__13573.o \
    $(BUILD_DIR)/asm/text/pf_service__13575.o \
    $(BUILD_DIR)/asm/text/pf_str__13577.o \
    $(BUILD_DIR)/asm/text/pf_driver__13588.o \
    $(BUILD_DIR)/asm/text/pdm_api.o \
    $(BUILD_DIR)/asm/text/pdm_bpb__13605.o \
    $(BUILD_DIR)/asm/text/pdm_disk__13608.o \
    $(BUILD_DIR)/asm/text/pdm_partition__13623.o \
    $(BUILD_DIR)/asm/text/pf_cache__13641.o \
    $(BUILD_DIR)/asm/text/pf_cluster__13674.o \
    $(BUILD_DIR)/asm/text/pf_dir__13676.o \
    $(BUILD_DIR)/asm/text/pf_entry__13689.o \
    $(BUILD_DIR)/asm/text/pf_entry_iterator__13709.o \
    $(BUILD_DIR)/asm/text/pf_fat__13720.o \
    $(BUILD_DIR)/asm/text/pf_fat12__13750.o \
    $(BUILD_DIR)/asm/text/pf_fat16__13754.o \
    $(BUILD_DIR)/asm/text/pf_fat32__13758.o \
    $(BUILD_DIR)/asm/text/pf_fatfs__13762.o \
    $(BUILD_DIR)/asm/text/pf_file__13763.o \
    $(BUILD_DIR)/asm/text/pf_path__13787.o \
    $(BUILD_DIR)/asm/text/Doubutsugo.o \
    $(BUILD_DIR)/asm/text/pf_sector__13814.o \
    $(BUILD_DIR)/asm/text/pf_volume__13818.o \
    $(BUILD_DIR)/asm/text/pf_volume_apiadd.o \
    $(BUILD_DIR)/asm/text/pf_cp932__13832.o \
    $(BUILD_DIR)/asm/text/pf_api_util__13838.o \
    $(BUILD_DIR)/asm/text/pf_attach__13843.o \
    $(BUILD_DIR)/asm/text/pf_closedir.o \
    $(BUILD_DIR)/asm/text/pf_errnum__13845.o \
    $(BUILD_DIR)/asm/text/pf_fclose__13846.o \
    $(BUILD_DIR)/asm/text/pf_fopen__13847.o \
    $(BUILD_DIR)/asm/text/pf_fread__13848.o \
    $(BUILD_DIR)/asm/text/pf_fseek__13849.o \
    $(BUILD_DIR)/asm/text/pf_fsfirst__13850.o \
    $(BUILD_DIR)/asm/text/pf_fsnext__13851.o \
    $(BUILD_DIR)/asm/text/pf_fstat__13852.o \
    $(BUILD_DIR)/asm/text/pf_fwrite__13853.o \
    $(BUILD_DIR)/asm/text/pf_getdev__13854.o \
    $(BUILD_DIR)/asm/text/pf_init_prfile2__13855.o \
    $(BUILD_DIR)/asm/text/pf_iswriteprotected.o \
    $(BUILD_DIR)/asm/text/pf_mkdir__13857.o \
    $(BUILD_DIR)/asm/text/pf_mount.o \
    $(BUILD_DIR)/asm/text/pf_opendir.o \
    $(BUILD_DIR)/asm/text/pf_remove__13860.o \
    $(BUILD_DIR)/asm/text/pf_unmount__13861.o \
    $(BUILD_DIR)/asm/text/pf_critical.o \
    $(BUILD_DIR)/asm/text/pf_filelock__13865.o \
    $(BUILD_DIR)/asm/text/pf_system__13867.o \
    $(BUILD_DIR)/asm/text/FAAttach.o \
    $(BUILD_DIR)/asm/text/FAClosedir.o \
    $(BUILD_DIR)/asm/text/FAErrnum.o \
    $(BUILD_DIR)/asm/text/FAFclose.o \
    $(BUILD_DIR)/asm/text/FAFopen.o \
    $(BUILD_DIR)/asm/text/FAFread.o \
    $(BUILD_DIR)/asm/text/FAFseek.o \
    $(BUILD_DIR)/asm/text/FAFsfirst.o \
    $(BUILD_DIR)/asm/text/FAFsnext.o \
    $(BUILD_DIR)/asm/text/FAFstat.o \
    $(BUILD_DIR)/asm/text/FAFwrite.o \
    $(BUILD_DIR)/asm/text/FAGetdev.o \
    $(BUILD_DIR)/asm/text/FAInit.o \
    $(BUILD_DIR)/asm/text/FAIsWriteProtected.o \
    $(BUILD_DIR)/asm/text/FAMkdir.o \
    $(BUILD_DIR)/asm/text/FAMount.o \
    $(BUILD_DIR)/asm/text/FAOpendir.o \
    $(BUILD_DIR)/asm/text/FARegistCB.o \
    $(BUILD_DIR)/asm/text/FARemove.o \
    $(BUILD_DIR)/asm/text/FAUnmount.o \
    $(BUILD_DIR)/asm/text/pfk_api.o \
    $(BUILD_DIR)/asm/text/nand_drv__13897.o \
    $(BUILD_DIR)/asm/text/sd_drv__13915.o \
    $(BUILD_DIR)/asm/text/pfd_cmn.o \
    $(BUILD_DIR)/asm/text/__mem.o \
    $(BUILD_DIR)/asm/text/__va_arg.o \
    $(BUILD_DIR)/asm/text/global_destructor_chain.o \
    $(BUILD_DIR)/asm/text/NMWException.o \
    $(BUILD_DIR)/asm/text/ptmf.o \
    $(BUILD_DIR)/asm/text/MWRTTI.o \
    $(BUILD_DIR)/asm/text/runtime.o \
    $(BUILD_DIR)/asm/text/__init_cpp_exceptions.o \
    $(BUILD_DIR)/asm/text/Gecko_ExceptionPPC.o \
    $(BUILD_DIR)/asm/text/GCN_mem_alloc.o \
    $(BUILD_DIR)/asm/text/alloc.o \
    $(BUILD_DIR)/asm/text/ansi_files.o \
    $(BUILD_DIR)/asm/text/ansi_fp.o \
    $(BUILD_DIR)/asm/text/arith.o \
    $(BUILD_DIR)/asm/text/buffer_io.o \
    $(BUILD_DIR)/asm/text/direct_io.o \
    $(BUILD_DIR)/asm/text/file_io.o \
    $(BUILD_DIR)/asm/text/FILE_POS.o \
    $(BUILD_DIR)/asm/text/mbstring.o \
    $(BUILD_DIR)/asm/text/mem.o \
    $(BUILD_DIR)/asm/text/mem_funcs.o \
    $(BUILD_DIR)/asm/text/math_api.o \
    $(BUILD_DIR)/asm/text/misc_io.o \
    $(BUILD_DIR)/asm/text/printf.o \
    $(BUILD_DIR)/asm/text/qsort.o \
    $(BUILD_DIR)/asm/text/rand.o \
    $(BUILD_DIR)/asm/text/scanf.o \
    $(BUILD_DIR)/asm/text/signal.o \
    $(BUILD_DIR)/asm/text/string.o \
    $(BUILD_DIR)/asm/text/strtold.o \
    $(BUILD_DIR)/asm/text/strtoul.o \
    $(BUILD_DIR)/asm/text/wstring.o \
    $(BUILD_DIR)/asm/text/wchar_io.o \
    $(BUILD_DIR)/asm/text/uart_console_io_gcn.o \
    $(BUILD_DIR)/asm/text/abort_exit_ppc_eabi.o \
    $(BUILD_DIR)/asm/text/math_sun.o \
    $(BUILD_DIR)/asm/text/extras.o \
    $(BUILD_DIR)/asm/text/e_acos.o \
    $(BUILD_DIR)/asm/text/e_asin.o \
    $(BUILD_DIR)/asm/text/e_atan2.o \
    $(BUILD_DIR)/asm/text/e_fmod.o \
    $(BUILD_DIR)/asm/text/e_log.o \
    $(BUILD_DIR)/asm/text/e_log10.o \
    $(BUILD_DIR)/asm/text/e_pow.o \
    $(BUILD_DIR)/asm/text/e_rem_pio2.o \
    $(BUILD_DIR)/asm/text/k_cos.o \
    $(BUILD_DIR)/asm/text/k_rem_pio2.o \
    $(BUILD_DIR)/asm/text/k_sin.o \
    $(BUILD_DIR)/asm/text/k_tan.o \
    $(BUILD_DIR)/asm/text/s_atan.o \
    $(BUILD_DIR)/asm/text/s_ceil.o \
    $(BUILD_DIR)/asm/text/s_copysign.o \
    $(BUILD_DIR)/asm/text/s_cos.o \
    $(BUILD_DIR)/asm/text/s_floor.o \
    $(BUILD_DIR)/asm/text/s_frexp.o \
    $(BUILD_DIR)/asm/text/s_ldexp.o \
    $(BUILD_DIR)/asm/text/s_modf.o \
    $(BUILD_DIR)/asm/text/s_sin.o \
    $(BUILD_DIR)/asm/text/s_tan.o \
    $(BUILD_DIR)/asm/text/w_acos.o \
    $(BUILD_DIR)/asm/text/w_asin.o \
    $(BUILD_DIR)/asm/text/w_atan2.o \
    $(BUILD_DIR)/asm/text/w_fmod.o \
    $(BUILD_DIR)/asm/text/w_log10.o \
    $(BUILD_DIR)/asm/text/w_pow.o \
    $(BUILD_DIR)/asm/text/e_sqrt.o \
    $(BUILD_DIR)/asm/text/math_ppc.o \
    $(BUILD_DIR)/asm/text/w_sqrt.o \
    $(BUILD_DIR)/asm/text/mainloop.o \
    $(BUILD_DIR)/asm/text/nubevent.o \
    $(BUILD_DIR)/asm/text/nubinit.o \
    $(BUILD_DIR)/asm/text/msg.o \
    $(BUILD_DIR)/asm/text/msgbuf.o \
    $(BUILD_DIR)/asm/text/serpoll.o \
    $(BUILD_DIR)/asm/text/usr_put.o \
    $(BUILD_DIR)/asm/text/dispatch.o \
    $(BUILD_DIR)/asm/text/msghndlr.o \
    $(BUILD_DIR)/asm/text/support.o \
    $(BUILD_DIR)/asm/text/mutex_TRK.o \
    $(BUILD_DIR)/asm/text/notify.o \
    $(BUILD_DIR)/asm/text/flush_cache.o \
    $(BUILD_DIR)/asm/text/mem_TRK.o \
    $(BUILD_DIR)/asm/text/string_TRK.o \
    $(BUILD_DIR)/asm/text/targimpl.o \
    $(BUILD_DIR)/asm/text/mpc_7xx_603e.o \
    $(BUILD_DIR)/asm/text/mslsupp.o \
    $(BUILD_DIR)/asm/text/dolphin_trk.o \
    $(BUILD_DIR)/asm/text/main_TRK.o \
    $(BUILD_DIR)/asm/text/dolphin_trk_glue.o \
    $(BUILD_DIR)/asm/text/targcont.o \
    $(BUILD_DIR)/asm/text/target_options.o \
    $(BUILD_DIR)/asm/text/UDP_Stubs.o \
    $(BUILD_DIR)/asm/text/main__14305.o \
    $(BUILD_DIR)/asm/text/CircleBuffer.o \
    $(BUILD_DIR)/asm/text/MWCriticalSection_gc.o

CTORS_O_FILES := \
    $(BUILD_DIR)/asm/ctors.o

DTORS_O_FILES := \
    $(BUILD_DIR)/asm/dtors.o

RODATA_O_FILES := \
    $(BUILD_DIR)/asm/rodata.o

DATA_O_FILES := \
    $(BUILD_DIR)/asm/data.o

BSS_O_FILES := \
    $(BUILD_DIR)/asm/bss.o

SDATA_O_FILES := \
    $(BUILD_DIR)/asm/sdata.o

SBSS_O_FILES := \
    $(BUILD_DIR)/asm/sbss.o

SDATA2_O_FILES := \
    $(BUILD_DIR)/asm/sdata2.o

SBSS2_O_FILES := \
    $(BUILD_DIR)/asm/sbss2.o
